name: ratingus_mobile
description: "Платформа для дистанционного управления учебным процессом в школах"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  rxdart: ^0.27.7
  auto_route: ^8.1.2
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  appmetrica_plugin: ^2.0.0
  get_it: ^7.7.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^4.2.1
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/favicon.png"
  android: true

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - env/.env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
